version: '3.8'

services:
  backend:
    build: ./luma-backend
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./luma-backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - postgres

  frontend:
    build: ./luma-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./luma-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=luma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  mongodb_data:
  postgres_data: